version: '3.9'
services:
  pg_database:
    image: postgres:15
    volumes: 
     - ./tmp/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && yarn install && ./bin/dev"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on: 
      - pg_database
    environment:
      DB_HOST: pg_database
      DB_PASSWORD: admin
      DB_USER: postgres
    tty: true # for tailwind to watch changes
